fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=Cargo.lock");
    println!("cargo:rerun-if-changed=../proto/oyasumi-core.proto");
    println!("cargo:rerun-if-changed=../proto/overlay-sidecar.proto");
    println!("cargo:rerun-if-changed=../proto/elevated-sidecar.proto");

    configure_tonic_build();

    // Build tauri app
    tauri_build::build()
}

fn configure_tonic_build() {
    tonic_prost_build::configure()
        // Make sure structs and enums generated by prost are serializable to be returnable from Tauri commands
        // Structs
        .type_attribute(
            "NvmlDevice",
            "#[derive(serde::Serialize)] #[serde(rename_all = \"camelCase\")]",
        )
        .type_attribute(
            "AddNotificationRequest",
            "#[derive(serde::Serialize)] #[serde(rename_all = \"camelCase\")]",
        )
        .type_attribute(
            "AddNotificationResponse",
            "#[derive(serde::Serialize)] #[serde(rename_all = \"camelCase\")]",
        )
        // Enums
        .type_attribute("NvmlStatus", "#[derive(serde::Serialize)]")
        .type_attribute(
            "NvmlSetPowerManagementLimitError",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "SetMsiAfterburnerProfileError",
            "#[derive(serde::Serialize)]",
        )
        // Compile protobuf files
        .compile_protos(
            &[
                "../proto/oyasumi-core.proto",
                "../proto/overlay-sidecar.proto",
                "../proto/elevated-sidecar.proto",
            ],
            &["../proto/"],
        )
        .unwrap();
}
