// @generated by protobuf-ts 2.9.0 with parameter long_type_string,add_pb_suffix,force_server_none
// @generated from protobuf file "oyasumi-core.proto" (package "OyasumiCore", syntax proto3)
// tslint:disable
import type { RpcTransport } from '@protobuf-ts/runtime-rpc';
import type { ServiceInfo } from '@protobuf-ts/runtime-rpc';
import { OyasumiCore } from './oyasumi-core_pb';
import type { ElevatedSidecarStartArgs } from './oyasumi-core_pb';
import { stackIntercept } from '@protobuf-ts/runtime-rpc';
import type { Empty } from './oyasumi-core_pb';
import type { OverlaySidecarStartArgs } from './oyasumi-core_pb';
import type { UnaryCall } from '@protobuf-ts/runtime-rpc';
import type { RpcOptions } from '@protobuf-ts/runtime-rpc';
/**
 * @generated from protobuf service OyasumiCore.OyasumiCore
 */
export interface IOyasumiCoreClient {
  /**
   * @generated from protobuf rpc: OnOverlaySidecarStart(OyasumiCore.OverlaySidecarStartArgs) returns (OyasumiCore.Empty);
   */
  onOverlaySidecarStart(
    input: OverlaySidecarStartArgs,
    options?: RpcOptions
  ): UnaryCall<OverlaySidecarStartArgs, Empty>;
  /**
   * @generated from protobuf rpc: OnElevatedSidecarStart(OyasumiCore.ElevatedSidecarStartArgs) returns (OyasumiCore.Empty);
   */
  onElevatedSidecarStart(
    input: ElevatedSidecarStartArgs,
    options?: RpcOptions
  ): UnaryCall<ElevatedSidecarStartArgs, Empty>;
}
/**
 * @generated from protobuf service OyasumiCore.OyasumiCore
 */
export class OyasumiCoreClient implements IOyasumiCoreClient, ServiceInfo {
  typeName = OyasumiCore.typeName;
  methods = OyasumiCore.methods;
  options = OyasumiCore.options;
  constructor(private readonly _transport: RpcTransport) {}
  /**
   * @generated from protobuf rpc: OnOverlaySidecarStart(OyasumiCore.OverlaySidecarStartArgs) returns (OyasumiCore.Empty);
   */
  onOverlaySidecarStart(
    input: OverlaySidecarStartArgs,
    options?: RpcOptions
  ): UnaryCall<OverlaySidecarStartArgs, Empty> {
    const method = this.methods[0],
      opt = this._transport.mergeOptions(options);
    return stackIntercept<OverlaySidecarStartArgs, Empty>(
      'unary',
      this._transport,
      method,
      opt,
      input
    );
  }
  /**
   * @generated from protobuf rpc: OnElevatedSidecarStart(OyasumiCore.ElevatedSidecarStartArgs) returns (OyasumiCore.Empty);
   */
  onElevatedSidecarStart(
    input: ElevatedSidecarStartArgs,
    options?: RpcOptions
  ): UnaryCall<ElevatedSidecarStartArgs, Empty> {
    const method = this.methods[1],
      opt = this._transport.mergeOptions(options);
    return stackIntercept<ElevatedSidecarStartArgs, Empty>(
      'unary',
      this._transport,
      method,
      opt,
      input
    );
  }
}
